CREATE DATABASE IF NOT EXISTS blog;

USE blog;

DROP TABLE IF EXISTS ARTICLES;
CREATE TABLE ARTICLES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(255),
	DESCRIPTION TEXT
);

INSERT INTO ARTICLES VALUES (null, 'Article par défaut', 'Description à venir...');